# Generated by Django 2.2.4 on 2021-06-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euro21', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='bet_A',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='bet_B',
        ),
    ]
