# Generated by Django 2.2.4 on 2021-06-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro21', '0002_auto_20210608_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=20)),
                ('second', models.CharField(max_length=20)),
                ('third', models.CharField(max_length=20)),
                ('fourth', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
