# Generated by Django 2.2.4 on 2021-06-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro21', '0003_auto_20210614_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStagePicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('p1', models.CharField(max_length=20)),
                ('p2', models.CharField(max_length=20)),
                ('p3', models.CharField(max_length=20)),
                ('p4', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
