# Generated by Django 2.2.4 on 2021-06-19 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euro21', '0004_auto_20210618_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstagepicks',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='groupstagepicks',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='groupstagepicks',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='groupstagepicks',
            name='p4',
        ),
    ]
