# Generated by Django 2.2.4 on 2021-06-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro21', '0005_auto_20210618_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstagepicks',
            name='p1',
            field=models.CharField(blank='true', max_length=20),
        ),
        migrations.AddField(
            model_name='groupstagepicks',
            name='p2',
            field=models.CharField(blank='true', max_length=20),
        ),
        migrations.AddField(
            model_name='groupstagepicks',
            name='p3',
            field=models.CharField(blank='true', max_length=20),
        ),
        migrations.AddField(
            model_name='groupstagepicks',
            name='p4',
            field=models.CharField(blank='true', max_length=20),
        ),
    ]
