# Generated by Django 2.2.4 on 2021-06-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro21', '0006_auto_20210618_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstagepicks',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='groupstagepicks',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='groupstagepicks',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='groupstagepicks',
            name='p4',
        ),
        migrations.AddField(
            model_name='groupstagepicks',
            name='pick',
            field=models.CharField(blank='true', max_length=20),
        ),
        migrations.AddField(
            model_name='groupstagepicks',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
