# Generated by Django 2.2.4 on 2021-06-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('euro2020', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStagePicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('pick', models.CharField(blank='true', max_length=20)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
    ]
